axiomhq/next-axiom

- package-lock.json
- package.json
New Next projects on Vercel are created with that version. Before this
commit, people would have to upgrade next before being able to install
this package, even after creating a site.
> Downgrade next to ^12.1.4

- src/logger.ts
since we are falling back to console when no env vars are available, we decided to improve how the logs look when they are printed on the browser and on the terminal.
> enhance: pretty print on localhost

- README.md
- __tests__/log.test.ts
- package-lock.json
- package.json
- src/logger.ts
If you have fields you want to log with all messages, you can create an 
intermediate logger like this:
```js
const logger = log.with({ scope: 'user' })
logger.info('User logged in', { userId: 42 })
// { 
//   "level": "info", 
//   "_time": "2022-07-04T09:49:42Z", 
//   "message": "User logged in", 
//   "fields": {
//     "scope": "user",
//     "userId": 42,
//   }
// }
```
> Support attaching fields to an intermediate logger

- examples/logger/pages/api/edge.js
- src/withAxiom.ts
Edge functions have middleware signature and should be treated same way as a middleware instead of being handled as a lambda api function.
> Fix edge function compatibility

- package.json
- src/withAxiom.ts
(#29): logs and webvitals are not working when nextjs basePath is set.
As a solution for this, we would set basePath to false in our rewrites
so it would be able to rewrite the axiom endpoints without appending
the basePath as part of the rewrite.
> fix/#29: set basePath to false in rewritres

- src/logger.ts
- src/withAxiom.ts
we want to know whether the ingested logs are being sent
from frontend, lambda function or edge function. Setting the source
as part of the logs payload would allow us in the backend to read it
and set it in the ingested logs.
> set source as part of vercel information object

- __tests__/log.test.ts
- src/logger.ts
when arguments are spread like this `...args` it automatically converts to an objects, and then we lose the value. 
for example:
```
log.info('foo', 'bar') 
```
would result in `args = {0: 'b', 1: 'a', 2: 'r'}`
This PR, handles the arguments in the `_log` method and checks if its an object or not, if the passed args is not an object, it will be stored in `fields.args` as it is.
> handle non-object arguments

- src/logger.ts
while sending logs exceptions could happend, swallowing the exception ensures we don't interrupts customer apps or break api functions responses. We do the same in web-vitals. I am not sure though about removing await, need to think about it and do some testing.
> catch and swallow exceptions on fetch

- README.md
- __tests__/withAxiom.test.ts
- examples/logger/pages/serverSideProps.tsx
- src/index.ts
- src/platform/generic.ts
- src/withAxiom.ts
- Add withAxiomNextServerSidePropsHandler
- Export all withAxiom functions
- Change type signature for withAxiomNextApiHandler
- Change type signature for withAxiom
> Add a HOF for wrapping getServerSideProps handlers

- package-lock.json
- package.json
- src/index.ts
- src/webVitals.ts
This adds an optional `path` parameter to a new `reportWebVitalsWithPath` function allowing people to specify their own value (e.g. falling back to `window.location.pathname`.
Here's an example for people that want the actual path (not the next path):
```typescript
import { NextWebVitalsMetric } from 'next/app'
import { reportWebVitalsWithPath } from 'next-axiom'
export function reportWebVitals(metric: NextWebVitalsMetric) {
reportWebVitalsWithPath(metric, window.location.pathname)
}
```
This also bumps the version to 0.18.
> Allow route override in reportWebVitals, bump version

- examples/logger/app/api/dynamic/[id]/route.ts
- examples/logger/package-lock.json
- src/withAxiom.ts
- support for dynamic route segment for ``withAxiom``  and ``withAxiomRouteHandler``
> fix: Support for route segment withAxiom

- src/withAxiom.ts
The dynamic route in the example was failing when `withAxiom(param: NextConfig)` came before `withAxiom(NextHandler)`, reversing them did the trick.
See https://github.com/axiomhq/next-axiom/blob/9ec2a795b5d5e84b683c117e3a5058fb72573676/examples/logger/app/api/dynamic/%5Bid%5D/route.ts#L5
> fix(withAxiom): Change order, add return type

- package-lock.json
- package.json
- src/hooks.ts
- src/util.ts
- prevents logger being recreated on rerender by "deep memoizing" it based on config (ie comparing previous and new config by value, not reference) 
- installs Remeda for the `equals` function - mostly chose this lib because it's known to treeshake well. could also use lodash or write our own deepEquals to avoid the dependency.
> Dedupe logger

- README.md
A little update to the v0.x README to show that you need to install with `@0` at the end of the install command.
Also removed the warning for Web Vitals as the patch has been merged
> Update V0.x README to reflect up to date info

- src/logger.ts
- tests/vercelConfig.test.ts
Now that our vercel integration parses JSON we can utilize the log drain to send structured data. This will allow our users to send logs without having to do `console.log(stringify({message: '...'})`.
next-axiom will keep populating the events and attaching context/request meta as always.
some improvements we could do:
- log to console right away without the need to flush
- figure out a way to avoid causing field limits error.
note: this could be improved later on using the [transports](https://github.com/axiomhq/next-axiom/issues/142) logic mentioned in the linked issue.
> utilize log drain on vercel functions

- package-lock.json
- package.json
This PR bumps the version in package.json to `1.2.0`, in order to the release the feature of printing to console when vercel integration is enabled.
> prepare v1.2.0

- README.md
- examples/logger/error.tsx
- examples/logger/middleware.ts
- package.json
- src/config.ts
- src/logger.ts
- src/platform/base.ts
- src/platform/generic.ts
- src/platform/netlify.ts
- src/webVitals/webVitals.ts
- src/withAxiom.ts
- tests/vercelConfig.test.ts
This PR provides 2 methods to facilitate logging HTTP requests.
The docs and examples have been updated to:
- Ask the users to create `middleware.ts` so that HTTP requests could be captured
- Encourage the users to create `error.tsx` to capture routing errors.
This will introduce new sources:
- middleware
- error.tsx
> Improve traffic and error capturing

- README.md
The README was missing a proper ending on a code block 😉
> fix(README.md): add missing ``` to code block ending

- package-lock.json
- package.json
- src/logger.ts
- tests/vercelConfig.test.ts
As the pricing of Vercel's log drain has gone higher, the  utilization for API routes doesn't make sense anymore.
> Dropped Vercel's log drain utilization

- src/logger.ts
- src/platform/generic.ts
- src/platform/vercel.ts
If this env is set, next-axiom will send logs and web-vitals to the given endpoint. This can be useful if you want to bring your own function.
> feat: Add NEXT_PUBLIC_AXIOM_CUSTOM_ENDPOINT env

- README.md
There were no exports for `@/next-axiom/logger`, but rather in `next-axiom`.
```tsx
import { useLogger, LogLevel } from "next-axiom";
```
> nit: fix import

- README.md
- src/logger.ts
- src/withAxiom.ts
This PR introduces an optional configuration object that contains a `logRequestDetails` property to specify if and whether to include detailed request information. 
Example of usage
```ts
export const GET = withAxiomRouteHandler(
async () => {
return new Response("Hello World!");
},
{ logRequestDetails: true }
);
```
or 
```ts
export const GET = withAxiomRouteHandler(
async () => {
return new Response("Hello World!");
},
{ logRequestDetails: ['body', 'nextUrl'] }
);
```
> feat: Add  `logRequestDetails` option to withAxiomRouteHandler

- package-lock.json
- package.json
- src/withAxiom.ts
`AXIOM_EDGE_REPORT` doesn't seem to be needed anymore since reports for edge functions are now emitted correctly Vercel, this PR addresses that by removing the code associated with `AXIOM_EDGE_REPORT` also solves #171
> fix: remove edge reports in favor of vercel default reports

- package-lock.json
- package.json
- src/webVitals/index.ts
This PR stabilizes path in `useReportWebVitals` to only send metrics on hard navigation. 
Current implementation of `useReportWebVitals` get's triggered every time path changes without updating the vitals, this meant that vitals send were being duplicated on each soft navigation even though they are only measured on hard navigations, hence, we were seeing behaviors like the one reported on #234 
There seems to be [talks](https://developer.chrome.com/docs/web-platform/soft-navigations-experiment.) around having soft navigations registered for web vitals but there's no current implementation for it in `next/web-vitals.`
> fix: webVitals duplicate info 

- src/platform/vercel.ts
We noticed a bug that all client-side logs from our Vercel deployments are being sent with the metadata field vercel.env set to "production". This line looks to be the cause -- the Vercel config is only checking for the VERCEL_ENV environment variable, which isn't available in client components - so it falls back to the NODE_ENV which is "production" for both Vercel preview and production deployments. The corresponding client variable is NEXT_PUBLIC_VERCEL_ENV, so this PR changes the metadata to check for either NEXT_PUBLIC_VERCEL_ENV or VERCEL_ENV before falling back to NODE_ENV.
> Check NEXT_PUBLIC_VERCEL_ENV for platform metadata on Vercel config
